# Awesome Copilot Configuration File
# Generated on 2025-09-24T23:34:11.540Z
#
# This file uses effective state precedence:
# 1. Explicit item settings (true/false) override everything
# 2. Items not listed inherit from enabled collections
# 3. Otherwise items are disabled
#
# To use:
# - Enable collections for curated sets of related items
# - Explicitly set individual items to true/false to override collections
# - Items not mentioned will follow collection settings
#
# After configuring, run: awesome-copilot apply
#

version: "1.0"
project:
  name: "FleetForge"
  description: "FleetForge project with awesome-copilot enhancements for project management, databases, and containerization"
  output_directory: ".github"
prompts:
  ai-prompt-engineering-safety-review: true
  architecture-blueprint-generator: true
  aspnet-minimal-api-openapi: true
  az-cost-optimize: true
  azure-resource-health-diagnose: true
  boost-prompt: true
  breakdown-epic-arch: true
  breakdown-epic-pm: true
  breakdown-feature-implementation: true
  breakdown-feature-prd: true
  breakdown-plan: true
  breakdown-test: true
  clojure-add-to-memory: true
  code-exemplars-blueprint-generator: true
  comment-code-generate-a-tutorial: true
  containerize-aspnet-framework: true
  containerize-aspnetcore: true
  copilot-instructions-blueprint-generator: true
  cosmosdb-datamodeling: true
  create-agentsmd: true
  create-architectural-decision-record: true
  create-github-action-workflow-specification: true
  create-github-issue-feature-from-specification: true
  create-github-issues-feature-from-implementation-plan: true
  create-github-issues-for-unmet-specification-requirements: true
  create-github-pull-request-from-specification: true
  create-implementation-plan: true
  create-llms: true
  create-oo-component-documentation: true
  create-readme: true
  create-specification: true
  create-spring-boot-java-project: true
  create-spring-boot-kotlin-project: true
  create-technical-spike: true
  csharp-async: true
  csharp-docs: true
  csharp-mstest: true
  csharp-nunit: true
  csharp-tunit: true
  csharp-xunit: true
  declarative-agents: true
  documentation-writer: true
  dotnet-best-practices: true
  dotnet-design-pattern-review: true
  editorconfig: true
  ef-core: true
  first-ask: true
  folder-structure-blueprint-generator: true
  gen-specs-as-issues: true
  generate-custom-instructions-from-codebase: true
  git-flow-branch-creator: true
  git-porcelain-explain: true
  java-docs: true
  java-junit: true
  java-springboot: true
  javascript-typescript-jest: true
  kotlin-springboot: true
  mkdocs-translations: true
  multi-stage-dockerfile: true
  my-issues: true
  my-pull-requests: true
  next-intl-add-language: true
  playwright-automation-fill-in-form: true
  playwright-explore-website: true
  playwright-generate-test: true
  postgresql-code-review: true
  postgresql-optimization: true
  project-workflow-analysis-blueprint-generator: true
  prompt-builder: true
  readme-blueprint-generator: true
  remember: true
  remember-interactive-programming: true
  repo-story-time: true
  review-and-refactor: true
  sql-code-review: true
  sql-optimization: true
  suggest-awesome-github-copilot-chatmodes: true
  suggest-awesome-github-copilot-prompts: true
  technology-stack-blueprint-generator: true
  update-avm-modules-in-bicep: true
  update-implementation-plan: true
  update-llms: true
  update-markdown-file-index: true
  update-oo-component-documentation: true
  update-specification: true
instructions:
  ai-prompt-engineering-safety-best-practices: true
chatmodes:
  api-architect: true
  azure-saas-architect: true
  meta-agentic-project-scaffold: true
  principal-software-engineer: true
  prompt-builder: true
  prompt-engineer: true
  refine-issue: true
  specification: true
  tech-debt-remediation-plan: true
collections:
  azure-cloud-development: false
  csharp-dotnet-development: false
  database-data-management: true
  devops-oncall: true
  frontend-web-dev: false
  project-planning: true
  security-best-practices: true
  technical-spike: true
  testing-automation: true
