//go:build !ignore_autogenerated

/*
Copyright 2024 FleetForge Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellCapacity) DeepCopyInto(out *CellCapacity) {
	*out = *in
	if in.CPURequestPerCell != nil {
		in, out := &in.CPURequestPerCell, &out.CPURequestPerCell
		*out = new(string)
		**out = **in
	}
	if in.MemoryRequestPerCell != nil {
		in, out := &in.MemoryRequestPerCell, &out.MemoryRequestPerCell
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellCapacity.
func (in *CellCapacity) DeepCopy() *CellCapacity {
	if in == nil {
		return nil
	}
	out := new(CellCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CellStatus) DeepCopyInto(out *CellStatus) {
	*out = *in
	in.Boundaries.DeepCopyInto(&out.Boundaries)
	if in.ClusterName != nil {
		in, out := &in.ClusterName, &out.ClusterName
		*out = new(string)
		**out = **in
	}
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CellStatus.
func (in *CellStatus) DeepCopy() *CellStatus {
	if in == nil {
		return nil
	}
	out := new(CellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistenceConfiguration) DeepCopyInto(out *PersistenceConfiguration) {
	*out = *in
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistenceConfiguration.
func (in *PersistenceConfiguration) DeepCopy() *PersistenceConfiguration {
	if in == nil {
		return nil
	}
	out := new(PersistenceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingConfiguration) DeepCopyInto(out *ScalingConfiguration) {
	*out = *in
	if in.MinCells != nil {
		in, out := &in.MinCells, &out.MinCells
		*out = new(int32)
		**out = **in
	}
	if in.MaxCells != nil {
		in, out := &in.MaxCells, &out.MaxCells
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingConfiguration.
func (in *ScalingConfiguration) DeepCopy() *ScalingConfiguration {
	if in == nil {
		return nil
	}
	out := new(ScalingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorldBounds) DeepCopyInto(out *WorldBounds) {
	*out = *in
	if in.YMin != nil {
		in, out := &in.YMin, &out.YMin
		*out = new(float64)
		**out = **in
	}
	if in.YMax != nil {
		in, out := &in.YMax, &out.YMax
		*out = new(float64)
		**out = **in
	}
	if in.ZMin != nil {
		in, out := &in.ZMin, &out.ZMin
		*out = new(float64)
		**out = **in
	}
	if in.ZMax != nil {
		in, out := &in.ZMax, &out.ZMax
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorldBounds.
func (in *WorldBounds) DeepCopy() *WorldBounds {
	if in == nil {
		return nil
	}
	out := new(WorldBounds)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorldSpec) DeepCopyInto(out *WorldSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorldSpec.
func (in *WorldSpec) DeepCopy() *WorldSpec {
	if in == nil {
		return nil
	}
	out := new(WorldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorldSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorldSpecList) DeepCopyInto(out *WorldSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorldSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorldSpecList.
func (in *WorldSpecList) DeepCopy() *WorldSpecList {
	if in == nil {
		return nil
	}
	out := new(WorldSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorldSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorldSpecSpec) DeepCopyInto(out *WorldSpecSpec) {
	*out = *in
	in.Topology.DeepCopyInto(&out.Topology)
	in.Capacity.DeepCopyInto(&out.Capacity)
	in.Scaling.DeepCopyInto(&out.Scaling)
	in.Persistence.DeepCopyInto(&out.Persistence)
	if in.MultiClusterEnabled != nil {
		in, out := &in.MultiClusterEnabled, &out.MultiClusterEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorldSpecSpec.
func (in *WorldSpecSpec) DeepCopy() *WorldSpecSpec {
	if in == nil {
		return nil
	}
	out := new(WorldSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorldSpecStatus) DeepCopyInto(out *WorldSpecStatus) {
	*out = *in
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]CellStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorldSpecStatus.
func (in *WorldSpecStatus) DeepCopy() *WorldSpecStatus {
	if in == nil {
		return nil
	}
	out := new(WorldSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorldTopology) DeepCopyInto(out *WorldTopology) {
	*out = *in
	if in.MaxCellsPerCluster != nil {
		in, out := &in.MaxCellsPerCluster, &out.MaxCellsPerCluster
		*out = new(int32)
		**out = **in
	}
	in.WorldBoundaries.DeepCopyInto(&out.WorldBoundaries)
	if in.CellSize != nil {
		in, out := &in.CellSize, &out.CellSize
		*out = new(WorldBounds)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorldTopology.
func (in *WorldTopology) DeepCopy() *WorldTopology {
	if in == nil {
		return nil
	}
	out := new(WorldTopology)
	in.DeepCopyInto(out)
	return out
}
