name: Docs Dependency Review

on:
  schedule:
    - cron: '0 12 1 1,4,7,10 *'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  review:
    name: Quarterly Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install MkDocs toolchain
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate outdated package report
        id: audit
        run: |
          python - <<'PY'
          import datetime
          import json
          import os
          from pathlib import Path
          import subprocess
          import sys

          raw = subprocess.check_output([sys.executable, '-m', 'pip', 'list', '--outdated', '--format', 'json'], text=True)
          packages = json.loads(raw)

          report_lines = [
              '# Docs Dependency Review',
              '',
              f'Generated: {datetime.datetime.utcnow().isoformat()}Z',
              ''
          ]

          if packages:
              report_lines.extend([
                  '| Package | Installed | Latest |',
                  '| --- | --- | --- |'
              ])
              for pkg in sorted(packages, key=lambda item: item['name'].lower()):
                  report_lines.append(f"| {pkg['name']} | {pkg['version']} | {pkg['latest_version']} |")
              status = 'outdated'
          else:
              report_lines.append('All documentation dependencies are up to date.')
              status = 'current'

          summary = '\n'.join(report_lines)

          report_path = Path('docs-dependency-report.md')
          report_path.write_text(summary + '\n')

          summary_path = os.environ.get('GITHUB_STEP_SUMMARY')
          if summary_path:
              Path(summary_path).write_text(summary + '\n')

          Path('docs_dependency_status.txt').write_text(status + '\n')
          print(summary)
          PY

      - name: Upload dependency report
        uses: actions/upload-artifact@v4
        with:
          name: docs-dependency-review
          path: |
            docs-dependency-report.md
            docs_dependency_status.txt
          retention-days: 30
