name: Build Docs PDFs

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**/*.md'
      - '.github/workflows/docs-pdf.yml'

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc and tectonic
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          curl --proto '=https' --tlsv1.2 -sSf https://tectonic-installer.github.io/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Generate PDFs
        run: |
          make pdfs || { echo 'Make failed'; exit 1; }

      - name: Upload PDFs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-pdfs
          path: docs/*.pdf

      - name: Commit PDFs back (if changed)
        if: github.ref == 'refs/heads/main'
        run: |
          if git diff --quiet -- docs/*.pdf; then
            echo 'No PDF changes to commit.'
          else
            git config user.name 'github-actions'
            git config user.email 'actions@users.noreply.github.com'
            git add docs/*.pdf
            git commit -m 'chore(docs): update generated PDFs'
            git push
          fi
